"use strict";
var batman = "Batman";
var linternaVerde = "Linterna Verde";
var volcanNegro = "Volcan negro";
console.log(batman);
console.log(linternaVerde);
console.log(volcanNegro);
var concatenar = "Los heroes: " + batman + ", " + linternaVerde + ", " + volcanNegro;
var concat = "Los h\u00E9roes son: " + batman + ", " + linternaVerde + ", " + volcanNegro;
console.log(concatenar);
console.log(concat);
